# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PuppyLove' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PuppyLove
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'
  pod 'Firebase'
  pod 'SDWebImageSwiftUI'
  pod 'FirebaseFirestoreSwift'
  

  target 'PuppyLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PuppyLoveUITests' do
    # Pods for testing
  end

end
